apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: monitoring-app
spec:
  containers:
    - name: worker-pod
      image: job-worker
      imagePullPolicy: Never
      ports:
        - containerPort: 80
      env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_URL
          value: "redis://redis:6379"
