apiVersion: v1
kind: Service
metadata:
  name: stats-service
  labels:
    name: stats-service
    app: monitoring-app
spec:
  type: NodePort
  selector:
    name: stats-pod
    app: monitoring-app
  ports:
    - port: 80
      targetPort: 3002
      nodePort: 30003
