apiVersion: apps/v1
kind: Deployment
metadata:
  name: submitter-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-app
      component: submitter
  template:
    metadata:
      labels:
        app: monitoring-app
        component: submitter
    spec:
      containers:
        - name: submitter
          image: job-submitter
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: PORT
              value: "3000"
